modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/authmod/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://example.com/updates.json"
displayURL="https://github.com/authmod"
logoFile="logo.png"
credits="Inspired by AuthMe Bukkit plugin"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.authmod]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="SERVER"

[[dependencies.authmod]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="SERVER"

