name: Build AuthMod

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      
    - name: 设置JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: 赋予gradlew执行权限
      run: chmod +x gradlew
      
    - name: 使用Gradle构建
      run: ./gradlew build --no-daemon
      
    - name: 上传构建产物
      uses: actions/upload-artifact@v3
      with:
        name: authmod-jar
        path: build/libs/*.jar
        
    - name: 显示构建信息
      run: |
        echo "构建完成！"
        ls -lh build/libs/

