name: build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        run: ./gradlew build -x test

      - name: Upload jar artifacts
        uses: actions/upload-artifact@v4
        with:
          name: authmod-artifacts
          path: |
            build/libs/*.jar
          if-no-files-found: error
          overwrite: true

name: Build AuthMod

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      
    - name: 设置JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: 赋予gradlew执行权限
      run: chmod +x gradlew
      
    - name: 使用Gradle构建
      run: ./gradlew build --no-daemon
      
    - name: 上传构建产物
      uses: actions/upload-artifact@v3
      with:
        name: authmod-jar
        path: build/libs/*.jar
        
    - name: 显示构建信息
      run: |
        echo "构建完成！"
        ls -lh build/libs/

