name: Build AuthMod

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: 设置 Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: 赋予gradlew执行权限
        run: chmod +x gradlew

      - name: Gradle 版本
        run: ./gradlew --version -Dorg.gradle.java.home=$JAVA_HOME

      - name: 使用Gradle构建
        run: ./gradlew clean build --no-daemon -x test --stacktrace --info -Dorg.gradle.java.home=$JAVA_HOME

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: authmod-artifacts
          path: build/libs/*.jar
          if-no-files-found: error
          overwrite: true

      - name: 显示构建信息
        run: |
          echo "构建完成！"
          ls -lh build/libs/

